version: '3.1'

services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:      